server:
  port: 12380
spring:
  elasticsearch:
    rest:
      uris: 172.16.4.80:9200
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      group-id: log-consumer
      bootstrap-servers: 172.16.4.80:9092